version: 2
jobs:
  build:
    parameters:
      go-version:
        type: string
      golangci-lint-version:
        type: string
    working_directory: /go/src/github.com/StudioAquatan/kitwalk
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run:
          name: go mod download
          command: go mod download
      - save_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>
      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet
      - run:
          name: Run go test
          command: |
            echo "mode: atomic" > coverage.txt && \
              go list ./... | \
              xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && \
              tail -n +2 coverage.tmp >> coverage.txt' && \
              rm coverage.tmp
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  main:
    jobs:
      - build:
          go-version: "1.12.10"
          golangci-lint-version: "1.19.1"
