version: 2
jobs:
  build:
    working_directory: /go/src/github.com/StudioAquatan/kitwalk
    docker:
      - image: circleci/golang:1.12.10
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run:
          name: go mod download
          command: go mod download
      - save_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
      - run:
          name: Install dependencies
          command: |
            go get -u golang.org/x/tools/cmd/goimports
            go get -u github.com/golang/lint/golint
      - run:
          name: Run goimports
          command: test -z "$(goimports -d $(go list -f {{.Dir}} ./... | grep -v /vendor/) | tee /dev/stderr)"
      - run:
          name: Run golint
          command: golint -set_exit_status $(go list -f {{.Dir}} ./... | grep -v /vendor/)
      - run:
          name: Run go test
          command: |
            echo "mode: atomic" > coverage.txt && \
              go list ./... | \
              xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && \
              tail -n +2 coverage.tmp >> coverage.txt' && \
              rm coverage.tmp
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  main:
    jobs:
      - build
